version: '3'
services:
    web:
        image: "nginx:1.17.5"
        container_name: "upick_nginx"
        ports:
            - "10303:80"
        volumes:
            - ./:/var/www/html/
            - ./dockercnf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./dockercnf/nginx/ssl/:/etc/nginx/ssl/
        depends_on:
            - php
    php:
        build: ./dockercnf/php7.3-fpm/
        image: "upick-php:7.3-fpm"
        container_name: "upick_php"
        privileged: true
        volumes:
            - ./:/var/www/html/
        depends_on:
            - db
    db:
        image: mysql:5.7.28
        container_name: "upick_mysql"
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci     
        privileged: true
        volumes:
            - ./dockercnf/mysql5.7/db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: www.sky31.com
            MYSQL_DATABASE: upick

